# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: |
    echo "Getting Docker Version"
    docker version
    echo "$(DOCKER_BASE_BUILD_IMAGE):$(DOCKER_BASE_BUILD_IMAGE_TAG)"
  displayName: 'Get Docker Version'

- script: |
    pwd
    ls
    echo "Using $(DOCKER_BASE_BUILD_IMAGE), $(DOCKER_BASE_BUILD_IMAGE_TAG), $(DOCKER_BASE_RUNTIME_IMAGE), $(DOCKER_BASE_RUNTIME_IMAGE)"
    docker build \
      --build-arg BASE_BUILD_IMAGE=$(DOCKER_BASE_BUILD_IMAGE) \
      --build-arg BASE_BUILD_IMAGE_TAG=$(DOCKER_BASE_BUILD_IMAGE_TAG)" \
      --build-arg BASE_RUNTIME_IMAGE=$(DOCKER_BASE_BUILD_IMAGE) \
      --build-arg BASE_RUNTIME_IMAGE_TAG=$(DOCKER_BASE_BUILD_IMAGE_TAG)" \
      --tag $(DOCKER_REGISTRY_IMAGE):$(DOCKER_REGISTRY_IMAGE_TAG) \
      ./pipelines/aspnetcore
    docker image ls
  displayName: 'Build Docker Image'
