# ==================================================================
# Environment variables utilized in this Pipeline:
#
# DOCKER_BUILDKIT: Set to 1 to use new BuildKit capabilities
# DOCKER_REGISTRY_USERNAME: Username for registry login
# DOCKER_REGISTRY_TOKEN: Token/password used to log into registry
# DOCKER_REGISTRY_FQDN: Base reference for Registry ex. dtr.moby.org
# DOCKER_REGISTRY_IMAGE: Image reference ex. dtr.moby.org/moby/applicationA
# DOCKER_BASE_IMAGE_BUILD: Stage 1/Build base image ex. mcr.microsoft.com/dotnet/core/sdk:2.1
# DOCKER_BASE_IMAGE_RUNTIME: Stage 2/Runtime base image ex. mcr.microsoft.com/dotnet/core/aspnet:2.1
# DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE: Docker Content Trust variable
# DOCKER_CONTENT_TRUST_ROOT_PASSPHRASE: Docker Content Trust variable
# 
# ==================================================================

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - pipelines/app/*

pool:
  # vmImage: 'ubuntu-latest'
  name: 'Shared SE - Windows'

steps:
- script: |
    echo "Getting User"
    whoami
  displayName: 'Get User'

- script: |
    echo "Getting Docker Version"
    docker version
  displayName: 'Get Docker Version'

- script: |
    # Login to the Docker Trusted Registry
    docker login $(DOCKER_REGISTRY_FQDN) \
      --username $(DOCKER_REGISTRY_USERNAME) \
      --password $(DOCKER_REGISTRY_TOKEN)
  displayName: 'Login to Docker Trusted Registry'
  enabled: "false"

- script: |
    docker build `
      --tag $(DOCKER_REGISTRY_IMAGE):1 `
      .\pipelines\app\aspnetcore
  displayName: 'Build Docker Image'

- script: |
    docker push $(DOCKER_REGISTRY_IMAGE):1
  displayName: 'Push Docker Image'

- script: |
    docker image rm $(DOCKER_REGISTRY_IMAGE):"$(git rev-parse --short HEAD)"
  displayName: 'Tidy Up'