# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - pipelines/*

pool:
  # vmImage: 'ubuntu-latest'
  name: 'Shared SE - Linux'

steps:
- script: |
    echo "Getting Docker Version"
    docker version
  displayName: 'Get Docker Version'

- script: |
    docker build \
      --build-arg BASE_BUILD_IMAGE=$(DOCKER_BASE_BUILD_IMAGE) \
      --build-arg BASE_BUILD_IMAGE_TAG=$(DOCKER_BASE_BUILD_IMAGE_TAG) \
      --build-arg BASE_RUNTIME_IMAGE=$(DOCKER_BASE_RUNTIME_IMAGE) \
      --build-arg BASE_RUNTIME_IMAGE_TAG=$(DOCKER_BASE_RUNTIME_IMAGE_TAG) \
      --tag $(DOCKER_REGISTRY_IMAGE):"$(git rev-parse --short HEAD)" \
      ./pipelines/app/aspnetcore
  displayName: 'Build Docker Image'

- script: |
    # Login to the Docker Registry
    echo $(DOCKER_REGISTRY_TOKEN) | \
    docker login $(DOCKER_REGISTRY_FQDN) \
      --username $(DOCKER_REGISTRY_USERNAME) \
      --password-stdin
  displayName: 'Login to Docker Trusted Registry'

- task: DownloadSecureFile@1
  inputs:
    secureFile: 'ucp-bundle-azure-devops.zip'

- script: |
    echo "Unzipping the client bundle"
    cd $(Agent.TempDirectory)
    unzip \
      -d ./bundle \
      ucp-bundle-azure-devops.zip

    # Source client bundle
    cd ./bundle
    ls -a
    docker trust key load key.pem
    export DOCKER_CONTENT_TRUST=1
  displayName: 'Setup Docker Client Bundle'

- script: |      
    docker push $(DOCKER_REGISTRY_IMAGE):"$(git rev-parse --short HEAD)"
  displayName: 'Push Docker Image'
