# https://helm.sh/docs/using_helm/#example-deploy-tiller-in-a-namespace-restricted-to-deploying-resources-only-in-that-namespace
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: se-stevenfollis
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-manager
  namespace: se-stevenfollis
rules:
- apiGroups: ["", "batch", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-binding
  namespace: se-stevenfollis
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: se-stevenfollis
roleRef:
  kind: Role
  name: tiller-manager
  apiGroup: rbac.authorization.k8s.io